# Generated by Django 4.2.13 on 2024-06-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sop',
        ),
    ]
